language: python
dist: trusty

cache: pip

python:
  - '3.6'
  - '3.6-dev'
  - 'nightly'

install:
  - python -c "import pip, sys; pip.main(['install', 'aiohttp', 'ujson', 'uvloop'])"

script: python setup.py test
